---
title: "Wastewater, Model Work"
author: "`Marlin derived from work by Brian Yandell"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 2,
	fig.width = 3,
	message = FALSE,
	warning = FALSE
)
```

```
The code was derived from work by the DSI. This analysis seeks to model % of tests positive using wastewater Data. This model has logical reasons to be predictive but only finds moderate success when broken down by collection site. Particularly it consistently underpredicts the % positive rate in the P2 district.
The Original R code file can be found in the [pandemic github repository](https://github.com/UW-Madison-DataScience/pandemic/blob/master/wastewater.Rmd).
The Code for this R File can be found in the [Marlin Lee waste Water Work](https://github.com/MarlinRLee/Covid-Waste-Water-Exploration/blob/main/general%20model%20finding.Rmd)
```




```{r}
library(tidyverse)
library(readxl)
library(broom)
library(zoo)
library(RcppRoll)
library(ggformula)
library(ggpubr)
kprint <- function(...) {
  if(interactive()) {
    print(...)
  } else {
    knitr::kable(...)
  }
}
```

```{r}

source("./DataProccess.R")


Waterfilename <- "../data/WW SARS-COV-2 Data V3.xlsx"
CovidFileName = "../data/MMSD_Cases.csv"
water=WasteWater(Waterfilename)
covidData=CovidData(CovidFileName)


```

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=8}
myplots <- list()
#,color="turquoise"
myplots[[1]]=
  ggplot(data=water)+
  aes(x=Date)+
  geom_line(aes(y=log10(PMMoV),color="PMMoV"))+
  geom_line(aes(y=log10(AVG),color="AVG"))+ scale_color_manual(values=c("red","turquoise"))+
  geom_point(aes(y=log10(AVG)),color="red",size=1)+
  geom_point(aes(y=log10(PMMoV)),color="turquoise",size=1)+
  geom_point(aes(y=log10(N1),shape="N1"))+
  geom_point(aes(y=log10(N2),shape="N2"))+scale_shape_manual(values=c(1,3))+
  scale_x_date(limits = c(as.Date("2020-9-4"),as.Date("2021-1-10")),labels = date_format("%b"))+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.title.x=element_blank(),
        legend.title = element_blank())+
  ylab("log10 marker concentration (cp/L)")+
  facet_grid(~Site)

myplots[[2]]= ggplot(data=water)+
  aes(x=Date)+
  geom_col(aes(y=Pct_BCoV))+
  scale_x_date(limits = c(as.Date("2020-9-4"),as.Date("2021-1-10")),labels = date_format("%b"))+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ylab("BCoV recovery (%) ")+
  facet_grid(~Site) + 
theme(
  strip.background = element_blank(),
  strip.text.x = element_blank()
) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggarrange(plotlist = myplots,ncol = 1, nrow = 2,common.legend=T,legend="bottom",heights=c(2,1))



```

