---
title: "Wastewater, Model Work"
author: "`Marlin derived from work by Brian Yandell"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 2,
	fig.width = 3,
	message = FALSE,
	warning = FALSE
)
```

```
The code was derived from work by the DSI. This analysis seeks to model % of tests positive using wastewater Data. This model has logical reasons to be predictive but only finds moderate success when broken down by collection site. Particularly it consistently underpredicts the % positive rate in the P2 district.
The Original R code file can be found in the [pandemic github repository](https://github.com/UW-Madison-DataScience/pandemic/blob/master/wastewater.Rmd).
The Code for this R File can be found in the [Marlin Lee waste Water Work](https://github.com/MarlinRLee/Covid-Waste-Water-Exploration/blob/main/general%20model%20finding.Rmd)
```




```{r}
library(tidyverse)
library(readxl)
library(broom)
library(zoo)
library(RcppRoll)
library(ggformula)
library(ggpubr)
kprint <- function(...) {
  if(interactive()) {
    print(...)
  } else {
    knitr::kable(...)
  }
}
```

```{r}

source("./DataProccess.R")


Waterfilename <- "data/WW SARS-COV-2 Data V3.xlsx"
CovidFileName = "data/covid.csv"
water=WasteWater(Waterfilename)
covidData=CovidData(CovidFileName)
  
```


#Conductivity, TSS, pH, Total_Flow, N1, N2, AVG, PMMoV, Pct_BCoV, TSS (mg/L)
#ToDo:
#1/2 looking at R^2 over a bunch of timeshifts
#1)
# Model W/O Site: log(N1), log(PMMoV), log(N2), #Total_Flow or log(Total_Flow)
# add: Compare smooth cases vs smooth model
#2)
# Devide P2 and compare
#3)
# try to define 3
#new questions:
#How to use Site // How to involve TotalFlow
#old questions
#TSS // P2 // Shifting
Curves

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=12}

####Fills in missing n2 values
N2Fixer = lm(N2~N1, data=water)
water$temp=predict.lm(N2Fixer,water,interval="none")
water=water%>%
  mutate(N2=ifelse(is.na(N2),temp,N2))
water=water%>%
  select(-temp)
###


#Moves the waterwaste data to match up trends
ShiftedAmount=8
#10 vs -18
print(paste("Time shifted",ShiftedAmount,"Days"))


water2=water%>%
  mutate(Date=as.Date(Date))%>%
  mutate(Date=Date+ShiftedAmount)

MergedData=left_join(covidData,water2,by = c("Date","Site"))%>%
  filter(Site!="UW-LakeShore",Site!="UW-Sellery", Site!="Madison")


Inner=inner_join(covidData,water2,by = c("Date","Site"))%>%
    filter(Site!="UW-LakeShore",Site!="UW-Sellery")
LInner = lm(roll ~ log(N2)+log(N1)+log(PMMoV)+log(Total_Flow)+Site, data=Inner)


MergedData$fittedMo=c(tail(predict.lm(LInner,MergedData,interval="none"), -ShiftedAmount), rep(NA, ShiftedAmount))
MergedData$fitted=predict.lm(LInner,MergedData,interval="none")


AdjustedData=MergedData
print(paste("R^2:",summary(LInner)$r.squared))

#gives the ranges of data for graph movements
StartTesting=as.Date("2020-4-11")
EndTesting=as.Date("2021-1-4")
StartFeces=as.Date("2020-9-20")
EndFeces=as.Date("2020-11-25")+ShiftedAmount

minSew=min(AdjustedData$Model,na.rm=TRUE)
maxSew=max(AdjustedData$Model,na.rm=T)
minTest=min(AdjustedData$roll,na.rm=T)
maxTest=max(AdjustedData$roll,na.rm=T)
sites=unique(AdjustedData$Site)

LInner

myplots <- list()
for (i in 1:length(sites)){
  SiteData=AdjustedData%>%
    filter(Site==sites[i])
  myplots[[i]]=
    ggplot(data=SiteData)+aes(x=Date)+
    #geom_point(aes(y=roll-fitted))+
    #geom_point(aes(y=roll,colour="Percent Positive"))+
    #geom_point(aes(y=fitted,colour="Model"))+
    geom_smooth(aes(y=roll,colour="Percent Positive"))+
    #geom_smooth(aes(y=fitted,colour="Model"))+
    geom_smooth(aes(y=fittedMo,colour="Model unmoved"))+
    ylab("% of Covid Tests Positive")+
    #scale_x_date(limits = c(StartFeces,EndFeces),labels = date_format("%b"))+
    ggtitle(sites[i])
}
annotate_figure(ggarrange(plotlist = myplots,ncol = 2, nrow = 3),top = text_grob(paste("R^2:",round(summary(LInner)$r.squared,2)), color = "red", face = "bold", size = 14))

ggplot(data=AdjustedData)+aes(x=Date,color=Site)+geom_point(aes(y=roll))+geom_point(aes(y=fittedMo),shape=2)+ylab("% of Covid Tests Positive")



ggplot(data=AdjustedData)+aes(x=Date)+geom_smooth(aes(y=roll))+geom_smooth(aes(y=fittedMo),shape=2)+ylab("% of Covid Tests Positive")
```

Points

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=12}


myplots <- list()
for (i in 1:length(sites)){
  SiteData=AdjustedData%>%
    filter(Site==sites[i])
  myplots[[i]]=
    ggplot(data=SiteData)+aes(x=Date)+
    #geom_point(aes(y=roll-fitted))+
    geom_point(aes(y=Cases,colour="Percent Positive"))+
    #geom_point(aes(y=fitted,colour="Model"))+
    geom_point(aes(y=fittedMo,colour="Model unmoved"))+
    ylab("Number of cases")+
    scale_x_date(limits = c(StartFeces,EndFeces),labels = date_format("%b"))+
    ggtitle(sites[i])
}
#ggtitle(text_grob(sites[i], color = "red", face = "bold", size = 14))

annotate_figure(ggarrange(plotlist = myplots,ncol = 2, nrow = 3),top = text_grob(paste("R^2:",round(summary(LInner)$r.squared,2)), color = "red", face = "bold", size = 14))


# AdjustedData%>%
#   ggplot()+aes(x=Date)+
#   geom_point(aes(y=PMMoV))+
#   scale_x_date(limits = c(StartFeces,EndFeces),labels = date_format("%b"))+
#   facet_wrap(~Site)

#look for 
```