---
title: "Wastewater, Model Work"
author: "`Marlin derived from work by Brian Yandell"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 2,
	fig.width = 3,
	message = FALSE,
	warning = FALSE
)
```

```
The code was derived from work by the DSI. This analysis seeks to model % of tests positive using wastewater Data. This model has logical reasons to be predictive but only finds moderate success when broken down by collection site. Particularly it consistently underpredicts the % positive rate in the P2 district.
The Original R code file can be found in the [pandemic github repository](https://github.com/UW-Madison-DataScience/pandemic/blob/master/wastewater.Rmd).
The Code for this R File can be found in the [Marlin Lee waste Water Work](https://github.com/MarlinRLee/Covid-Waste-Water-Exploration/blob/main/general%20model%20finding.Rmd)
```




```{r}
library(tidyverse)
library(readxl)
library(broom)
library(zoo)
library(RcppRoll)
library(ggformula)
library(ggpubr)
kprint <- function(...) {
  if(interactive()) {
    print(...)
  } else {
    knitr::kable(...)
  }
}
```

```{r 2}
filename <- "../../data/wastewater/WW SARS-COV-2 Data V3.xlsx"
#filename <- "data/wastewater/UW and MMSD Report for SARS-Cov-2 Influent Samples 12.08.20vFinal.xlsx"
```

```{r warning = FALSE, message = FALSE}
tmpfn <- function(N1, N2) {
  AVG <- sqrt(N1 * N2)
  AVG <- ifelse(is.na(N1), N2, AVG)
  AVG <- ifelse(is.na(N2), N1, AVG)
}
missing_codes <- c("","NA","0","Undetected","Not Detected",
                   "Field Parameters to be filled in", 
                   "Inhibited-to be re-ran", "#DIV/0!")
sheets <- excel_sheets(filename)
water_MMSD <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), "text"),
                    sheet = 1) %>%
  rename(Comment = "...12")
water_Interceptors <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 8), "text"),
                    sheet = 2) %>%
  rename(Comment = "...11") %>%
  mutate(TSS = NA,
         Site = ifelse(Site == "MMSD P02", "MMSD P2", Site),
         Site = ifelse(Site == "MMSD P07", "MMSD P7", Site),
         Site = ifelse(Site == "MMSD P08", "MMSD P8", Site)) %>%
  select(1:5, TSS, everything())
water_UW_Dorms <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), rep("text", 1)),
                    sheet = 3) %>%
  rename(Comment = "...12")
water <- 
  bind_rows(water_MMSD,
            water_Interceptors,
            water_UW_Dorms) %>%
  rename(Date = "Collection Date",
         pH = "pH (SU)",
         Total_Flow = "Total Flow (MGD)",
         Conductivity = "Conductivity (uS/CM@25C)",
         N1 = "N1 (GC/L)",
         N2 = "N2 (GC/L)",
         PMMoV = "PMMoV (GC/L)",
         Pct_BCoV = "% Recovery (BCoV)") %>%
  filter(!is.na(Site)) %>%
  mutate(AVG = tmpfn(N1, N2),
         wt = 2 - is.na(N1) - is.na(N2),
         Site = ifelse(Site == "UW-D", "UW-LakeShore", Site),
         Site = ifelse(Site == "UW-S", "UW-Sellery", Site))
```

```{r}
waters <- water %>%
  pivot_longer(Conductivity:Pct_BCoV, names_to = "assay", values_to = "values") %>%
  filter(!is.na(values)) %>%
  mutate(wt = ifelse(assay == "AVG", wt, 1))
```

```{r}
predfn <- function(x) {
  x$pred <- 10^predict(lm(log10(values) ~ Date + Site, x, weight = wt))
  x
}
addpred <- function(x) {
  bind_rows(
    map(
      split(x, x$assay),
      predfn),
    .id = "assay")
}
```

```{r}
fitfn <- function(x, add = FALSE, ...) {
  if(add) {
    form <- formula(log10(values) ~ Date + Site)
    elems <- 2:3
    test <- "drop1"
  } else {
    form <- formula(log10(values) ~ Date * Site)
    elems <- 3
    test <- "anova"
  }
  fit <- lm(form, x, weight = wt)
  switch(test,
         anova = broom::tidy(anova(fit)[elems,]),
         drop1 = broom::tidy(drop1(fit, fit, test = "F")[elems,])) %>%
    select(term, statistic, p.value) %>%
    mutate(statistic = round(statistic, 2),
           p.value = signif(p.value, 3))
}
sumfn <- function(x, ...) {
  bind_rows(
    map(
      split(x, x$assay),
      fitfn, ...),
    .id = "assay") %>%
    arrange(term, assay)
}
timefit <- function(x) {
  bind_rows(
    sumfn(x, TRUE),
    sumfn(x)) %>%
  select(-statistic) %>%
  pivot_wider(names_from = "term", values_from = "p.value") %>%
  kprint()
}
```


#Conductivity, TSS, pH, Total_Flow, N1, N2, AVG, PMMoV, Pct_BCoV, TSS (mg/L)
#ToDo:
#1/2 looking at R^2 over a bunch of timeshifts
#1)
# Model W/O Site: log(N1), log(PMMoV), log(N2), #Total_Flow or log(Total_Flow)
# add: Compare smooth cases vs smooth model
#2)
# Devide P2 and compare
#3)
# try to define 3
#new questions:
#How to use Site // How to involve TotalFlow
#old questions
#TSS // P2 // Shifting
Curves

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=12}
#Moves the waterwaste data to match up trends
ShiftedAmount=10
#10 vs -18
print(paste("Time shifted",ShiftedAmount,"Days"))

CovidFileName = "../covid.csv"
covidData = read.csv(CovidFileName)%>%
  mutate(ServiceID = ifelse(ServiceID=="MMSD","Madison",paste("MMSD P",ServiceID,sep="")),Date = as.Date(Date , format = "%m/%d/%y"))%>%
  rename(Site=ServiceID)%>%
  group_by(Site)%>%
  #mutate(roll=rollmean(Cases/Tests,k = 1, fill = NA))
  mutate(roll=Cases/Tests)

water2=water%>%
  mutate(Date=as.Date(Date))%>%
  mutate(Date=Date+ShiftedAmount)

MergedData=left_join(covidData,water2,by = c("Date","Site"))%>%
  filter(Site!="UW-LakeShore",Site!="UW-Sellery", Site!="Madison")

sites=unique(MergedData$Site)


myplots <- list()
for (i in 1:length(sites)){
  Inner=inner_join(covidData,water2,by = c("Date","Site"))%>%
    filter(Site==sites[i])
  LInner = lm(roll ~ log(N2)+log(N1)+log(PMMoV), data=Inner)

  MergedData$fitted=predict.lm(LInner,MergedData,interval="none")

  AdjustedData=MergedData
  R2=round(summary(LInner)$r.squared,2)
  #gives the ranges of data for graph movements
  StartTesting=as.Date("2020-4-11")
  EndTesting=as.Date("2021-1-4")
  StartFeces=as.Date("2020-9-20")+ShiftedAmount
  EndFeces=as.Date("2020-11-25")+ShiftedAmount

  minTest=min(AdjustedData$roll,na.rm=T)
  maxTest=max(AdjustedData$roll,na.rm=T)
  
  SiteData=AdjustedData%>%
    filter(Site==sites[i])
  myplots[[i]]=
    ggplot(data=SiteData)+aes(x=Date)+
    #geom_point(aes(y=roll-fitted))+
    #geom_point(aes(y=roll,colour="Percent Positive"))+
    #geom_point(aes(y=fitted,colour="Model"))+
    geom_smooth(aes(y=roll,colour="Percent Positive"))+
    geom_smooth(aes(y=fitted,colour="Model"))+
    annotate(geom="label", x=StartFeces+ShiftedAmount, y=.025, label=paste("R^2:",R2), color="red")+
    ylab("% of Covid Tests Positive")+
    ylim(minTest,maxTest)+
    scale_x_date(limits = c(StartFeces,EndFeces),labels = date_format("%b"))+
    ggtitle(sites[i])

}

ggarrange(plotlist = myplots,ncol = 2, nrow = 3)

```

Points

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=12}

myplots <- list()
for (i in 1:length(sites)){
  Inner=inner_join(covidData,water2,by = c("Date","Site"))%>%
    filter(Site==sites[i])
  LInner = lm(roll ~ log(N2)+log(N1)+log(PMMoV), data=Inner)

  MergedData$fitted=predict.lm(LInner,MergedData,interval="none")

  AdjustedData=MergedData
  R2=round(summary(LInner)$r.squared,2)
  #gives the ranges of data for graph movements
  StartTesting=as.Date("2020-4-11")
  EndTesting=as.Date("2021-1-4")
  StartFeces=as.Date("2020-9-20")+ShiftedAmount
  EndFeces=as.Date("2020-11-25")+ShiftedAmount

  minTest=min(AdjustedData$roll,na.rm=T)
  maxTest=max(AdjustedData$roll,na.rm=T)
  
  SiteData=AdjustedData%>%
    filter(Site==sites[i])
  myplots[[i]]=
    ggplot(data=SiteData)+aes(x=Date)+
    geom_point(aes(y=roll,colour="Percent Positive"))+
    geom_point(aes(y=fitted,colour="Model"))+
    #geom_smooth(aes(y=roll,colour="Percent Positive"))+
    #geom_smooth(aes(y=fitted,colour="Model"))+
    annotate(geom="label", x=StartFeces+ShiftedAmount, y=.025, label=paste("R^2:",R2), color="red")+
    ylab("% of Covid Tests Positive")+
    ylim(minTest,maxTest)+
    scale_x_date(limits = c(StartFeces,EndFeces),labels = date_format("%b"))+
    ggtitle(sites[i])

}

ggarrange(plotlist = myplots,ncol = 2, nrow = 3)
```