---
title: "N1 predict N2"
author: "`Marlin derived from work by Brian Yandell"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 2,
	fig.width = 3,
	message = FALSE,
	warning = FALSE
)
```

```
The code was derived from work by the DSI. This analysis seeks to model % of tests positive using wastewater Data. This model has logical reasons to be predictive but only finds moderate success when broken down by collection site. Particularly it consistently underpredicts the % positive rate in the P2 district.
The Original R code file can be found in the [pandemic github repository](https://github.com/UW-Madison-DataScience/pandemic/blob/master/wastewater.Rmd).
The Code for this R File can be found in the [Marlin Lee waste Water Work](https://github.com/MarlinRLee/Covid-Waste-Water-Exploration/blob/main/general%20model%20finding.Rmd)
```




```{r}
library(lme4)
library(arm)
library(MuMIn)


library(tidyverse)
library(readxl)
library(broom)
library(zoo)
library(RcppRoll)
library(ggformula)
library(ggpubr)
kprint <- function(...) {
  if(interactive()) {
    print(...)
  } else {
    knitr::kable(...)
  }
}
```

```{r 2}
filename <- "data/WW SARS-COV-2 Data V3.xlsx"
CovidFileName = "data/covid.csv"
#filename <- "data/wastewater/UW and MMSD Report for SARS-Cov-2 Influent Samples 12.08.20vFinal.xlsx"
```

```{r warning = FALSE, message = FALSE}
missing_codes <- c("","NA","0","Undetected","Not Detected",
                   "Field Parameters to be filled in", 
                   "Inhibited-to be re-ran", "#DIV/0!")
sheets <- excel_sheets(filename)
water_MMSD <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), "text"),
                    sheet = 1) %>%
  rename(Comment = "...12")
water_Interceptors <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 8), "text"),
                    sheet = 2) %>%
  rename(Comment = "...11") %>%
  mutate(TSS = NA,
         Site = ifelse(Site == "MMSD P02", "MMSD P2", Site),
         Site = ifelse(Site == "MMSD P07", "MMSD P7", Site),
         Site = ifelse(Site == "MMSD P08", "MMSD P8", Site)) %>%
  select(1:5, TSS, everything())
water_UW_Dorms <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), rep("text", 1)),
                    sheet = 3) %>%
  rename(Comment = "...12")
water <- 
  bind_rows(water_MMSD,
            water_Interceptors,
            water_UW_Dorms) %>%
  rename(Date = "Collection Date",
         pH = "pH (SU)",
         Total_Flow = "Total Flow (MGD)",
         Conductivity = "Conductivity (uS/CM@25C)",
         N1 = "N1 (GC/L)",
         N2 = "N2 (GC/L)",
         PMMoV = "PMMoV (GC/L)",
         Pct_BCoV = "% Recovery (BCoV)") %>%
  filter(!is.na(Site)) %>%
  mutate(Site = ifelse(Site == "UW-D", "UW-LakeShore", Site),
         Site = ifelse(Site == "UW-S", "UW-Sellery", Site))
```

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




```{r}
water=water%>%
  filter(!(is.na(N2)&is.na(N1)))

DataPoints=length(water$N1)
N2Missing=water%>%
  filter(is.na(N2))
N2Missing=length(N2Missing$N2)
paste("Out of the",DataPoints,"Data points in the data base,",N2Missing,"N2 points are missing. This means the dataframe is missing",round(100*N2Missing/DataPoints),"Percent of the N2 data")
```

```{r, echo=FALSE, dpi=600, fig.width=12, fig.height=12}
water%>%
  ggplot()+aes(x=N1,N2)+
  geom_point()+
  stat_smooth(method = "lm", col = "red")+
  scale_x_log10()+
  scale_y_log10()
```


```{r, echo=FALSE, dpi=600, fig.width=8, fig.height=8}
####Fills in missing n2 values
N2Fixer = lm(N2~N1, data=water)
water$temp=predict.lm(N2Fixer,water,interval="none")
water2=water%>%
  mutate(N2=ifelse(is.na(N2),temp,N2))
###
summary(N2Fixer)
```

```{r, echo=FALSE, dpi=600, fig.width=8, fig.height=8}
water2%>%
  ggplot()+aes(x=Date,y=(N2-temp))+
  geom_point()+
  stat_smooth(method = "lm", col = "red")+
  ylab("Residual")

water2%>%
  ggplot()+aes(x=N1,y=(N2-temp))+
  geom_point()+
  scale_x_log10()+
  stat_smooth(method = "lm", col = "red")+
  ylab("Residual")
#3 topics:
#conductivity: negative trend on our end or noise
#N1->n2
#paper: Yale says through may time shift. N1 N2 smooths lowess/loess
#-cases is 7, hospitalization is 4 days
#-distributed time lag serious /Bayesian framework
#preprint non shifted
```