---
title: "Wastewater, R^2 heatmap"
author: "`Marlin derived from work by Brian Yandell"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 7,
	fig.width = 15,
	message = FALSE,
	warning = FALSE
)
#what the results?
#discription
#git tag
#string name
```

```
The code was derived from work by the DSI. Creates a heatmap of the R^2 of diffrent models with diffrent time delays.



The Original R code file can be found in the [pandemic github repository](https://github.com/UW-Madison-DataScience/pandemic/blob/master/wastewater.Rmd).
The Code for this R File can be found in the [Marlin Lee waste Water Work](https://github.com/MarlinRLee/Covid-Waste-Water-Exploration/blob/main/general%20model%20finding.Rmd)
```




```{r}
library(tidyverse)
library(readxl)
library(broom)
library(zoo)
library(RcppRoll)
library(ggformula)
library(ggpubr)
library(heatmap3)
kprint <- function(...) {
  if(interactive()) {
    print(...)
  } else {
    knitr::kable(...)
  }
}
```

```{r 2}
filename <- "../../data/wastewater/WW SARS-COV-2 Data V3.xlsx"
#filename <- "data/wastewater/UW and MMSD Report for SARS-Cov-2 Influent Samples 12.08.20vFinal.xlsx"
```

```{r warning = FALSE, message = FALSE}
tmpfn <- function(N1, N2) {
  AVG <- sqrt(N1 * N2)
  AVG <- ifelse(is.na(N1), N2, AVG)
  AVG <- ifelse(is.na(N2), N1, AVG)
}
missing_codes <- c("","NA","0","Undetected","Not Detected",
                   "Field Parameters to be filled in", 
                   "Inhibited-to be re-ran", "#DIV/0!")
sheets <- excel_sheets(filename)
water_MMSD <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), "text"),
                    sheet = 1) %>%
  rename(Comment = "...12")
water_Interceptors <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 8), "text"),
                    sheet = 2) %>%
  rename(Comment = "...11") %>%
  mutate(TSS = NA,
         Site = ifelse(Site == "MMSD P02", "MMSD P2", Site),
         Site = ifelse(Site == "MMSD P07", "MMSD P7", Site),
         Site = ifelse(Site == "MMSD P08", "MMSD P8", Site)) %>%
  select(1:5, TSS, everything())
water_UW_Dorms <- read_excel(filename,
                    na = missing_codes,
                    col_types = c("text", "date", rep("numeric", 9), rep("text", 1)),
                    sheet = 3) %>%
  rename(Comment = "...12")
water <- 
  bind_rows(water_MMSD,
            water_Interceptors,
            water_UW_Dorms) %>%
  rename(Date = "Collection Date",
         pH = "pH (SU)",
         Total_Flow = "Total Flow (MGD)",
         Conductivity = "Conductivity (uS/CM@25C)",
         N1 = "N1 (GC/L)",
         N2 = "N2 (GC/L)",
         PMMoV = "PMMoV (GC/L)",
         Pct_BCoV = "% Recovery (BCoV)") %>%
  filter(!is.na(Site)) %>%
  mutate(AVG = tmpfn(N1, N2),
         wt = 2 - is.na(N1) - is.na(N2),
         Site = ifelse(Site == "UW-D", "UW-LakeShore", Site),
         Site = ifelse(Site == "UW-S", "UW-Sellery", Site))
```

```{r}
ShiftData=function(D,ShiftedAmount){
  D%>%
  mutate(Date=as.Date(Date))%>%
  mutate(Date=Date+ShiftedAmount)
}

CovidFileName = "../covid.csv"
covidData = read.csv(CovidFileName)%>%
  mutate(ServiceID = ifelse(ServiceID=="MMSD","Madison",paste("MMSD P",ServiceID,sep="")),Date = as.Date(Date , format = "%m/%d/%y"))%>%
  rename(Site=ServiceID)%>%
  group_by(Site)%>%
  mutate(roll=rollmean(Cases/Tests,k = 7, fill = NA))


Model_Names=c("log(N1)+log(PMMoV) + Site + Total_Flow","log(N1)+log(PMMoV)+ Site","log(N1) +log(PMMoV)+ Site + Total_Flow+log(N2)","Site")

```

```{r}
MaxTimeSkip=60
cols=length(Model_Names)
skip=5
output = matrix(ncol=cols+1, nrow=MaxTimeSkip/skip)
for(i in 1:(MaxTimeSkip/skip)) {
  for(j in 1:cols) {
  M=skip*i-MaxTimeSkip%/%2
  Inner=inner_join(covidData,ShiftData(water,M),by = c("Date","Site"))
  if (j==1){
    LInner = lm(roll ~ log(N1)+log(PMMoV) + Site, data=Inner)
  }
  if (j==2){
    LInner = lm(roll ~ log(N1)+log(PMMoV)+ Site + Total_Flow, data=Inner)
  }
  if (j==3){
    LInner = lm(roll ~ log(N2)+log(N1)+log(PMMoV)+Site+Total_Flow, data=Inner)
  }
  if (j==4){
    LInner = lm(roll ~ Site, data=Inner)
  }
  output[i,1]=M
  output[i,j+1]=summary(LInner)$r.squared
  }
}
outputa = data.frame(output)
ColNames=c("Offset",Model_Names)
colnames(outputa)=ColNames
#output

#LInner
#How complete a picture
#narrow down for contrast
#get map to tell story
#get hierarchy framework
#10 linear models with cross interactions
#
```
17         22
waste ->   pop
pop       
comment out vs build into a pipe 



```{r}
outputa%>%
  pivot_longer('log(N1)+log(PMMoV) + Site + Total_Flow':'Site',names_to="Models",values_to = "values")%>%
  ggplot()+
  geom_tile(aes(x=Offset,y=Models,fill=values))+
  scale_fill_gradient(low = "black",
  high = "white")

#find heatmap package:
#heat map2
#use color for more use
#automatically shorting
```

